name: Deploy to Surge parcial

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and Deploy
      run: npm install --global surge
    
    -name: Deploy surge 
     run: surge --token ${{ secrets.SURGE_TOKEN }} --project ./ --domain scary-sugar.surge.sh

        
